[package]
name = "configuration"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
prost = "0.14.1"



[build-dependencies]
transmission = { path = "../transmission" }