[package]
name = "configuration"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
prost = "0.14.1"



[build-dependencies]
transmission = { path = "../transmission" }