[package]
name = "constants"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
directories-next = "2.0.0"
figment = { version = "0.10.19", features = ["toml"] }
once_cell = "1.21.3"
