[package]
name = "mod_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.2", features = ["rayon"] }
quick-xml = { version = "0.38.1", features = ["async-tokio"] }
rayon = "1.11.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.20.0"
