[package]
name = "transmission"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
serde = { version = "1.0.219", features = ["derive"] }

[build-dependencies]
prost-build = "0.14.1"
